#!/bin/bash

cd _yay_ast

echo "Compiling pgen"

gcc -I Parser -I Include $(python3-config --includes) \
    -o pgen \
    Parser/acceler.c \
    Parser/grammar1.c \
    Parser/node.c \
    Parser/parser.c \
    Parser/bitset.c \
    Parser/grammar.c \
    Pgen/listnode.c \
    Pgen/metagrammar.c \
    Pgen/firstsets.c \
    Pgen/pgen.c \
    Pgen/obmalloc.c \
    Pgen/dynamic_annotations.c \
    Pgen/mysnprintf.c \
    Pgen/pyctype.c \
    Pgen/tokenizer_pgen.c \
    Pgen/printgrammar.c \
    Pgen/parsetok_pgen.c \
    Pgen/pgenmain.c

echo "Done compiling pgen"
echo "Running pgen"

./pgen Grammar/Grammar Include/graminit.h Python/graminit.c

echo "Done making graminit"
